### PR TITLE
Add cross-platform support for pre/post version script hooks.

### LINKED ISSUE #2: Support npm script preversion, version, and postversion
I've begun using this module as a replacement for `npm version`, but what I'm missing is the auto running npm scripts when I use `npm version` (a la: https://docs.npmjs.com/cli/version)

Be great if running them could be added in the same order of operation. I'm willing to give that implementation a shot too, let me know if you want me to start investigating

### PR DESCRIPTION
**Pull request by webuniverseio**
Also fix error reporting for exec function that was failing when result `stdout` and `stderr` are null (for example in case when `ENOENT` error is surfaced). Fixes: https://github.com/BigstickCarpet/version-bump-prompt/issues/2

### CODE REVIEW

**Comment by webuniverseio** [comment]
@BigstickCarpet , what do you think?

**Comment by JamesMessinger** [comment]
@szarouski - Thanks for the PR.  It looks good, but if you could add a couple more things, I'd really appreciate it.

__Script order__
To fully reproduce the behavior of `npm version`, it should perform the [steps that are listed here](https://docs.npmjs.com/cli/version).  Specifically:
  1. Run the `preversion` script before the version is updated (and before the version prompt is shown)
  2. Run the `version` script after the version is updated, but _before_ `git commit` and `git tag`
  3. Run the `postversion` script after `git commit` and `git tag`, but _before_ `git push`

__Tests__
Please add a few tests for this new functionality.  The tests currently work by [modifying the PATH variable](https://github.com/BigstickCarpet/version-bump-prompt/blob/master/tests/fixtures/helper.js#L59-L62) to run a [dummy git binary](https://github.com/BigstickCarpet/version-bump-prompt/blob/master/tests/fixtures/bin/git) that just writes its arguments to a text file.  Then [this function](https://github.com/BigstickCarpet/version-bump-prompt/blob/master/tests/fixtures/helper.js#L109-L126) is called to assert that git was run with the expected arguments.  The same approach should be taken with npm, so we can assert that npm is being called as expected.

**Comment by webuniverseio** [comment]
@BigstickCarpet Ok, I'll try. First I had to make tests run on windows: https://ci.appveyor.com/project/szarouski/version-bump-prompt. I added appveyor CI (with a little bit of pain). Would you mind dropping support for node < 4? I can make it working, but it require more time and I'm not sure it is much needed. Worst case people can submit another PR.

**Comment by webuniverseio** [comment]
@BigstickCarpet Please review again.

**Comment by JamesMessinger** [comment]
@szarouski - Thanks for all your work on this.  I haven't had a chance to review your latest commits yet (been too busy at work), but should be able to look at them next week.  Sorry for the delay :(

Thanks for adding appveyor CI.  I've been meaning to do that anyway. 👍 

I'm fine with dropping support for old Node versions (< 4.0).   Just update the [`engines`](https://docs.npmjs.com/files/package.json#engines) settings in the package.json file accordingly.

Thanks again!

**Comment by webuniverseio** [comment]
No problem, I'm happy to contribute 😄. I updated engines setting.

**Comment by JamesMessinger** [comment]
@szarouski - I've finally got some free time, so I'm merging this PR now.  Will make some additional changes and then publish it to npm as v3.0.0

**Comment by JamesMessinger** [comment]
@szarouski - v3.0.0 has been published to npm.   Thanks again for your help!  I gave you credit in [the changelog](https://github.com/BigstickCarpet/version-bump-prompt/blob/master/CHANGELOG.md#v300-2016-12-25) 👍

**Pull request merged**
